### ISSUE TITLE
IllegalStateException: Couldn't identify test class in call stack.

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#268]
I'm getting issues while trying to use Recheck on my project. My project is a TestNG and has a rule to name tests that I suspect its related. See attached simple project reproducing the issue.

`# Created at 2019-07-05T09:14:16.485
org.testng.TestNGException: 
Cannot instantiate class com.xxxx.basetest.DirectLoginTestNGTest
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:30)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:423)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
	at org.testng.TestClass.getInstances(TestClass.java:95)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:81)
	at org.testng.TestClass.init(TestClass.java:73)
	at org.testng.TestClass.<init>(TestClass.java:38)
	at org.testng.TestRunner.initMethods(TestRunner.java:389)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:24)
	... 28 more
Caused by: java.lang.IllegalStateException: Couldn't identify test class in call stack. 
This is needed to dynamically name the Golden Master files. 
 Please instantiate RecheckImpl with RecheckOptions, and provide a different FileNamerStrategy.
	at de.retest.recheck.FileNamerStrategy.lambda$getTestClassName$0(FileNamerStrategy.java:29)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at de.retest.recheck.FileNamerStrategy.getTestClassName(FileNamerStrategy.java:29)
	at de.retest.recheck.RecheckOptions.$default$suiteName(RecheckOptions.java:7)
	at de.retest.recheck.RecheckOptions.<init>(RecheckOptions.java:7)
	at de.retest.recheck.RecheckOptions$RecheckOptionsBuilderImpl.build(RecheckOptions.java:7)
	at com.xxxx.basetest.BaseTest.<init>(BaseTest.java:133)
	at com.xxxx.basetest.ConsoleLoginTest.<init>(ConsoleLoginTest.java:23)
	at com.xxxx.basetest.DirectLoginTestNGTest.<init>(DirectLoginTestNGTest.java:11)
	... 33 more`

[RecheckError.zip](https://github.com/retest/recheck-web/files/3363099/RecheckError.zip)

**Comment by javydreamercsw** [comment]
I tried following the suggestions and created the configuration as follows without success:
`
     @Getter
      private Recheck recheck = new RecheckImpl(RecheckOptions.builder().fileNamerStrategy(new 
      FileNamerStrategy()
  {
    @Override
    public String getTestClassName()
    {
      return getTestName();
    }

    @Override
    public String getTestMethodName()
    {
      return FileNamerStrategy.super.getTestMethodName(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public FileNamer createFileNamer(String... baseNames)
    {
      return new FileNamer()
      {
        @Override
        public File getFile(final String extension)
        {
          return toFile(DEFAULT_RETEST_PROJECT_PATH, extension, baseNames);
        }

        @Override
        public File getResultFile(final String extension)
        {
          return toFile(DEFAULT_RETEST_TESTREPORTS_PATH, extension, baseNames);
        }

        private File toFile(final String prefix, final String extension, 
                final String... baseNames)
        {
          final String baseName = String.join(File.separator, baseNames);
          return new File(prefix + File.separator + RECHECK_FOLDER_NAME 
                  + File.separator + baseName + extension);
        }
      };
    }
  }).build());
`

**Comment by beatngu13** [comment]
Hey @javydreamercsw,

Thanks for the detailed issue report!

As you already assumed correctly, the test fails because recheck cannot determine the test class/method name. We do this by searching for particular annotations (such as TestNG's `@Test`) in the call stack. We assumed that one would initialize fields via e.g. `@BeforeMethod`, not directly. So if you adapt your test as follows, everything should be fine:

```java
public class SampleTest implements ITest {

	private final ThreadLocal<String> testName = new ThreadLocal<>();

	@Getter
	private Recheck recheck;

	@BeforeMethod
	public void BeforeMethod( final Method method, final Object[] testData ) {
		recheck = new RecheckImpl();

		if ( testData == null || testData.length == 0 ) {
			testName.set( String.format( "%s", method.getName() ) );
		} else {
			testName.set( String.format( "%s %s", method.getName(), Arrays.toString( testData ) ) );
		}
	}

	// ...
}
```

Alternatively, you can also implement a custom `FileNamerStrategy`—which you already did. I believe the problem here is your implementation of `getTestMethodName()`. You call `super`, which again uses our default mechanism that doesn't work in your case. However, you could do something like:

```java
public class SampleTest implements ITest {

	private class MyCustomFileNamer implements FileNamerStrategy {

		private final ITest iTest;

		public MyCustomFileNamer( final ITest iTest ) {
			this.iTest = iTest;
		}

		@Override
		public String getTestClassName() {
			return iTest.getClass().getName();
		}

		@Override
		public String getTestMethodName() {
			return iTest.getTestName();
		}

		@Override
		public FileNamer createFileNamer( final String... baseNames ) {
			// Reuse an existing file namer or implement your own.
			return new MavenConformFileNamerStrategy().createFileNamer( baseNames );
		}

	}

	private final ThreadLocal<String> testName = new ThreadLocal<>();

	@Getter
	private final Recheck recheck = new RecheckImpl( RecheckOptions.builder() //
			.fileNamerStrategy( new MyCustomFileNamer( this ) ) //
			.build() );

	// ...
}
```

Please let us know if this helps.

**Comment by javydreamercsw** [comment]
At least I got past the error with your changes (only tried the first option). Sadly I didn't see the detailed report.
`BaseTestNGTest.testRecheck:366 A detailed report will be created at '/Users/javierortiz/Documents/P14C/environment-tool-automation-framework/target/test-classes/retest/recheck/com.xxx.basetest.BaseTest.report'. You can review the details by using our CLI (https://github.com/retest/recheck.cli/) or GUI (https://retest.de/review/).`

This is the test I tried:
`getRecheck().startTest("unit-test");
    
    getSeleniumInterface().getWebDriver().get("https://google.com");
    
    getRecheck().check(getSeleniumInterface().getWebDriver(), "step-1" );
    
    getRecheck().capTest();`

**Comment by beatngu13** [comment]
Hmmm, I cannot produce this issue locally. Based on your sample project, I've used the following `pom.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.pingidentity</groupId>
	<artifactId>RecheckError</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
			<scope>test</scope>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.8</version>
			<scope>test</scope>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.141.59</version>
			<scope>test</scope>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>de.retest</groupId>
			<artifactId>recheck-web</artifactId>
			<version>1.1.0</version>
			<scope>test</scope>
			<type>jar</type>
		</dependency>
	</dependencies>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>
</project>
```

And the following test class:

```java
package com.recheckerror;

import java.lang.reflect.Method;
import java.util.Arrays;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.ITest;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import de.retest.recheck.Recheck;
import de.retest.recheck.RecheckImpl;

public class SampleTest implements ITest {

	private final ThreadLocal<String> testName = new ThreadLocal<>();

	private Recheck recheck;
	private WebDriver webDriver;

	@Override
	public String getTestName() {
		return testName.get();
	}

	@BeforeMethod
	public void beforeMethod( final Method method, final Object[] testData ) {
		recheck = new RecheckImpl();
		webDriver = new ChromeDriver();

		if ( testData == null || testData.length == 0 ) {
			testName.set( String.format( "%s", method.getName() ) );
		} else {
			testName.set( String.format( "%s %s", method.getName(), Arrays.toString( testData ) ) );
		}
	}

	@Test
	public void test() {
		recheck.startTest( "unit-test" );

		webDriver.get( "https://google.com" );

		recheck.check( webDriver, "step-1" );

		recheck.capTest();

	}

	@AfterMethod
	public void afterMethod( final Method method, final Object[] testData ) {
		recheck.cap();
		webDriver.quit();
	}

}
```

After creating the Golden Master and running the test again, I get a report under the path given by recheck.

**Comment by javydreamercsw** [comment]
It's there. Was looking at wrong project.
