### ISSUE TITLE
Error on findElement by id

### ISSUE THREAD

**Issue by lhimo** [retest/recheck-web#272]
I'm trying to compile the provided example, but I get the following error at the line `driver.findElement( By.id( "intro-slider" ) );`

```
Wed Jul 10 14:04:49 CEST 2019:ERROR:java.lang.NoSuchMethodError: de.retest.recheck.TestCaseFinder.findTestCaseMethodInStack()Ljava/lang/StackTraceElement;
   java.lang.NoSuchMethodError: de.retest.recheck.TestCaseFinder.findTestCaseMethodInStack()Ljava/lang/StackTraceElement;
   	at de.retest.web.selenium.TestHealer.writeWarnLogForChangedIdentifier(TestHealer.java:211)
   	at de.retest.web.selenium.TestHealer.findElementById(TestHealer.java:84)
   	at de.retest.web.selenium.TestHealer.findElement(TestHealer.java:54)
   	at de.retest.web.selenium.TestHealer.findElement(TestHealer.java:49)
   	at de.retest.web.selenium.UnbreakableDriver.findElement(UnbreakableDriver.java:88)
   	at org.openqa.selenium.WebDriver$findElement$1.call(Unknown Source)
   	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
   	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
   	at de.retest.web.it.Script16.run(Script16.groovy:127)
   	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:90)
   	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
   	at com.eviware.soapui.impl.wsdl.panels.teststeps.GroovyScriptStepDesktopPanel$RunAction$1.run(GroovyScriptStepDesktopPanel.java:250)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   	at java.lang.Thread.run(Unknown Source)

```

**Comment by beatngu13** [comment]
Did you manually add recheck 1.2.0 as a dependency? If yes, remove it and let recheck-web pull it's own (compatible) recheck dependency. If you have to do this by yourself, use recheck-web 1.1.0 JAR along with recheck 1.1.1 JAR.

**Comment by lhimo** [comment]
Thanks, sorry I moved to recheck-web since it was happening only with unbreakable driver. It seems to be working fine!
