### ISSUE TITLE
Argument is of an illegal type: de.retest.web.selenium.WebElementWrapper

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#290]
This is related to #288 . Trying to run UnbreakableDriver.executeScript lets to the error below. I assume it's not unwrapping the proxy before passing it down.

Here's the relevant stack trace:
`java.lang.IllegalArgumentException: Argument is of an illegal type: de.retest.web.selenium.WebElementWrapper
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:484)
	at de.retest.web.selenium.UnbreakableDriver.executeScript(UnbreakableDriver.java:231)`

I'm using recheck-web 1.3.0.

**Comment by javydreamercsw** [comment]
The call is triggered from a WebDriverEventListener with the following code:

`@Override
  public void beforeClickOn(WebElement arg0, WebDriver arg1)
  {
((JavascriptExecutor) arg1).executeScript("return window.scrollY;", fromElement);
}`

**Comment by roesslerj** [comment]
Thanks for bringing that to our attention.

**Comment by roesslerj** [comment]
Addressed in PR https://github.com/retest/recheck-web/pull/305

**Comment by roesslerj** [comment]
Fixe in 1.3.1.
