### ISSUE TITLE
NoClassDefFoundError exception when calling re.check()

### ISSUE THREAD

**Issue by sdanes1** [retest/recheck-web#350]
Getting the below exception when calling .check(). I even tried using just the example from the github page and still get exact same error. I've tried 1.5.0-beta.2 and 1.5.0-beta.1. I'm on a mac if it makes a difference. The exception is: 
`java.lang.NoClassDefFoundError: org/openqa/selenium/WrapsElement
	at de.retest.web.RecheckSeleniumAdapter.canCheck(RecheckSeleniumAdapter.java:56)
	at de.retest.recheck.execution.RecheckAdapters.lambda$findAdapterFor$0(RecheckAdapters.java:16)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
	at de.retest.recheck.execution.RecheckAdapters.findAdapterFor(RecheckAdapters.java:17)
	at de.retest.recheck.RecheckImpl.check(RecheckImpl.java:117)
	at com.tmobile.he.tests.customer.CustomerSanity.itShouldLoginWithValidCredentials(CustomerSanity.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.WrapsElement
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more`

**Comment by diba1013** [comment]
You seem to be using maven. A `java.lang.NoClassDefFoundError: org/openqa/selenium/WrapsElement` is typically an indicator for a older version of a dependency. Sadly the [javadoc](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WrapsElement.html) does not specify the version in which it was introduced.

While recheck-web uses maven, too, and defines the [3.141.59](https://github.com/retest/recheck-web/blob/master/pom.xml#L100) version of Selenium, it can be overwritten by your specified version, as maven will take the first encounter of a dependency.

Could you tell me if and what version you have specified for Selenium and if it is available within your test-cycle (i.e. TestNG)? You can find your dependency within the pom or the project tree of your IDE.
Also it might help, to define the recheck-web dependency further on top.

**Comment by sdanes1** [comment]
Thanks this helped a lot! Our framework is based upon a lower level corporate wide java framework. It is using Selenium 3.8.1. Unfortunately our version of the framework (specifically in its global logging) has trouble with the newer version of Selenium. I will work with our centralized team to see if I can get our version of Selenium caught up. Thanks again for the assist!

**Comment by diba1013** [comment]
Depending on your setup you could also consider (maybe just for evaluation purposes) to create a separate project with only recheck-web and run your website locally or connect via an url. That would remove the conflict within the project. That's what we are doing with our own website: [retest.de-tests](https://github.com/retest/retest.de-tests). We are currently running those tests against our live website (as we currently do not have different stages). You might have different staging environments where you can run the tests against the development site or even a quality assurance site.

An example test can be found [here](https://github.com/retest/retest.de-tests/blob/master/src/test/java/de/retest/recheck/RetestWebpageTest.java).
```
WebDriver driver = new ChromeDriver();
driver.get( url );
```

**Comment by beatngu13** [comment]
@diba1013 @roesslerj maybe we should consider going back to the "internal" variants of `WrapsElement` and `WrapsDriver`:

* https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/internal/WrapsDriver.html
* https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/internal/WrapsElement.html

Although these classes are now marked as being deprecated, this would be both backwards and forwards compatible.

**Comment by roesslerj** [comment]
Good idea. I support that.

**Comment by beatngu13** [comment]
@sdanes1 next beta/stable should be backwards-compatible, would mind giving us feedback if I let you know as soon as the release is available?

**Comment by sdanes1** [comment]
@beatngu13 No problem at all, just let me know! Thanks for the quick attention!

**Comment by beatngu13** [comment]
@sdanes1 new beta is now available (also on Maven Central): https://github.com/retest/recheck-web/releases/tag/v1.5.0-beta.3

**Comment by roesslerj** [comment]
Seems to cause other issues now (https://github.com/retest/recheck-web/issues/352)...

**Comment by sdanes1** [comment]
Also gives new exception with the older version of Selenium; 
`org.openqa.selenium.JavascriptException: javascript error: Cannot read property 'align-self' of null
  (Session info: chrome=74.0.3729.108)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'TXRICMAC0699747.local', ip: 'fe80:0:0:0:18ed:1134:bc20:90bf%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 74.0.3729.6 (255758eccf3d24..., userDataDir: C:\Users\ADMINI~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:49754}, handlesAlerts: true, hasMetadata: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(pac: http://127.0.0.1..., rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 74.0.3729.108, webStorageEnabled: true, webdriver.remote.sessionid: bd66936d5e0440a1b452f03d278...}
Session ID: bd66936d5e0440a1b452f03d27846a89
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:537)
	at de.retest.web.RecheckSeleniumAdapter.convert(RecheckSeleniumAdapter.java:109)
	at de.retest.web.RecheckSeleniumAdapter.convertWebDriver(RecheckSeleniumAdapter.java:96)
	at de.retest.web.RecheckSeleniumAdapter.convert(RecheckSeleniumAdapter.java:89)
	at de.retest.web.RecheckSeleniumAdapter.convert(RecheckSeleniumAdapter.java:86)
	at de.retest.recheck.persistence.RecheckSutState.convert(RecheckSutState.java:25)
	at de.retest.recheck.RecheckImpl.createActionReplayResult(RecheckImpl.java:138)
	at de.retest.recheck.RecheckImpl.check(RecheckImpl.java:126)
	at de.retest.recheck.RecheckImpl.check(RecheckImpl.java:116)`

**Comment by roesslerj** [comment]
Ok, but this is a different problem. If you don't mind, I'll move this to a separate issue and close this one.

**Comment by roesslerj** [comment]
Separate issue for the javascript error is https://github.com/retest/recheck-web/issues/355

**Comment by roesslerj** [comment]
@sdanes1 could you provide some more information about this here: #355?

**Comment by roesslerj** [comment]
Hello @sdanes1,

I just wanted to check back what your experience with recheck-web is so far. Anything else we can improve? Any problems? If you want, you can instead mail me at roessler@retest.de.

I would be very happy and very grateful for any kind of feedback.

Thanks!
Jeremy
