### ISSUE TITLE
Version 1.5.0-beta 2: Error opening report

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#351]
Just tried the change to only screen shot the WebElement and works perfectly! Just had to add a NameStrategy like suggested.

But got a report loading exception:

```
Exception loading a Report

java.lang.ClassCastException: class java.lang.Float cannot be cast to class de.retest.recheck.persistence.Persistable (java.lang.Float is in module java.base of loader 'bootstrap'; de.retest.recheck.persistence.Persistable is in unnamed module of loader 'app')
	at de.retest.recheck.persistence.bin.KryoPersistence.load(SourceFile:52)
	at de.retest.recheck.persistence.PersistenceFactory$DynamicLoadPersistenceProxy.load(SourceFile:85)
	at de.retest.report.LoadTestReportFromInputFlow.a(SourceFile:83)
	at de.retest.report.LoadTestReportFromInputFlow.a(SourceFile:135)
	at de.retest.report.LoadTestReportFromInputFlow.a(SourceFile:75)
	at de.retest.report.LoadTestReportFromInputFlow.a(SourceFile:53)
	at de.retest.gui.review.workers.LoadTestReportWorker.a(SourceFile:69)
	at de.retest.gui.review.workers.LoadTestReportWorker.doInBackground(SourceFile:39)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
Created from #326

**Comment by javydreamercsw** [comment]
Review tool is not compatible with 1.5+
