### ISSUE TITLE
java.lang.ClassCastException: de.retest.recheck.persistence.ClassAndMethodBasedNamingStrategy cannot be cast to de.retest.web.selenium.AutocheckingCheckNamingStrategy

### ISSUE THREAD

**Issue by Sha-123** [retest/recheck-web#476]
*Before submission, please check that ...*

- [ ] this is related specifically to recheck-web and [recheck](https://github.com/retest/recheck) itself.
- [ ] the [documentation](https://docs.retest.de/) does not mention a similar solution (e.g. possible configurations).
- [ ] there are no open or closed issues that are related to this idea.
- [ ] this, to my best knowledge, will not break something else.

**Comment by Sha-123** [comment]
I am getting this issues when running tests in version 1.5

**Comment by Sha-123** [comment]
![Recheck](https://user-images.githubusercontent.com/36278770/71445618-0183e500-2741-11ea-9b89-bdd4547e421f.png)

**Comment by diba1013** [comment]
Thanks for reporting this issue. Sadly, we are not able to provide fixes for old version. Please try to verify that it appears with the [latest release](https://github.com/retest/recheck-web/releases). If you are not able to (due to incompatibilities), please provide a minimal code example as described below, so that we can verify the bug.

If it still occurred with the latest release, in order for us to reproduce and fix, please provide the stacktrace and a brief description of your code and approach, ideally via a minimal example (please make sure to remove any proprietary code). This should include:

1. The driver used and potentially wrapped drivers. From the log I am gathering you use the `ChromeDriver` as base, potentially wrapped in a `RecheckDriver`.
2. The `Recheck` instance created (with all `Recheck(Web)Options` provided.
3. The action or check where the exception occurs.

If it is easier for you, I could also take a look at (a part of) your project and try to come up with a solution in case of any usage errors. If so, please email me a link to your project or the project itself as minified archive. It should include the pom and the necessary test classes. Feel free to omit any proprietary code, however the above mentioned points should be readable.

For further information, please take a look at the [documentation](https://docs.retest.de/recheck-web/ways-of-using-recheck-web/).

**Comment by Sha-123** [comment]
I tried running test using recheck-web 1.8, but getting following logs. When i am using latest recheck-web version 1.5 or less getting java.lang.ClassCastException: de.retest.recheck.persistence.ClassAndMethodBasedNamingStrategy cannot be cast to de.retest.web.selenium.AutocheckingCheckNamingStrategy

[RemoteTestNG] detected TestNG version 7.0.0
org.testng.TestNGException: 
Cannot find class in classpath: Recheck.Correction.Browser
	at org.testng.xml.XmlClass.loadClass(XmlClass.java:75)
	at org.testng.xml.XmlClass.init(XmlClass.java:67)
	at org.testng.xml.XmlClass.<init>(XmlClass.java:54)
	at org.testng.xml.TestNGContentHandler.startElement(TestNGContentHandler.java:541)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at org.testng.xml.XMLParser.parse(XMLParser.java:39)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
	at org.testng.xml.Parser.parse(Parser.java:160)
	at org.testng.xml.Parser.parse(Parser.java:246)
	at org.testng.TestNG.parseSuite(TestNG.java:298)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:350)
	at org.testng.TestNG.initializeEverything(TestNG.java:980)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by Sha-123** [comment]
Please look at the code 
[Correction.zip](https://github.com/retest/recheck-web/files/4005063/Correction.zip)

**Comment by diba1013** [comment]
The above mentioned exception with `org.testng.TestNGException: Cannot find class in classpath: Recheck.Correction.Browser` occurs because TestNG expects test classes to be public.

Otherwise, I could not find any other exception with the provided project as is. The test runs on my machine with no other changes but the access modifier changed to public:
```diff
-class Browser{
+public class Browser{
```
which then produces the Golden Master `retest\recheck\Recheck.Correction.Browser\retest.00.recheck` with recheck-web version 1.5.0. When upgrading to recheck-web 1.8.0 the test still pass.

Please make the mentioned adaption and report back if your test still fails.

Couple of side notes:

1. We encourage the [following setup](https://docs.retest.de/recheck/introduction/usage/#testng) for your tests, ideally using the [TestNG hook](https://github.com/retest/recheck-testng-extension) to ensure the [lifecycle](https://docs.retest.de/recheck/introduction/usage/#lifecycle).
    1. Create your Driver in `@BeforeTest`
    2. Within your test method, go to the url specified. Ensure that `driver.startTest()` has been called before, either manually or via the above mentioned test extension.
    3. Call `driver.quit()`  in `@AfterTest`. This is to ensure the driver to be shutdown if the test method fails via an exception. Otherwise you will have several background processes running after a while.
2. Unless you are not reusing the driver, we encourage to call `driver.quit()` instead of `driver.close()` to make sure that the driver is properly shutdown.

For an overview, please refer to: https://docs.retest.de/recheck-web/introduction/usage/

**Comment by diba1013** [comment]
I assume this is fixed now, closing due to inactivity. If you or any other still have problems, please comment and reopen this issue.
